### ISSUE TITLE
Bool Error

### ISSUE THREAD

**Issue by passionyang16** [whoareyouwhoami/ProjectCasa#2]
run_test.py
when running : 
test.unit_all(start=6, end=10)

Following errors come out:

URL: 6
서울시
Apartment build date: 1997년 10월
Apartment construction company: 라인건설(주)
Apartment floor: 15층/20층
Apartment floor ratio: 309%
Apartment parking: 1.07대
Apartment address: 서울시 강서구 등촌동 628-15
apartment_builder: 라인건설(주)
apartment_build_year: 1997
apartment_build_month: 10
apartment_floor_ratio: 309
apartment_floor_min: 15
apartment_floor_max: 20
apartment_addr_province: 서울시
apartment_addr_district: 강서구
apartment_addr_town: 등촌동
apartment_parking: 1.07
Nearby school: 서울백석초등학교
Time to school: 도보로 16분
School address: 서울특별시 강서구 공항대로 491
Number of students: 534명(남 299명, 여 235명)
school_name: 서울백석초등학교
school_dist: 16
school_addr_province: 서울특별시
school_addr_district: 강서구
school_addr_town: 공항대로
school_students: 534

Traceback (most recent call last):
  File "/Users/jungyulyang/Documents/programming/pycharm/ProjectCasa/WebCrawling/run_test.py", line 62, in <module>
    test.unit_all(start=6, end=10)
  File "/Users/jungyulyang/Documents/programming/pycharm/ProjectCasa/WebCrawling/run_test.py", line 53, in unit_all
    self.landsite.web_collect()
  File "/Users/jungyulyang/Documents/programming/pycharm/ProjectCasa/WebCrawling/collect.py", line 64, in web_collect
    self._tower_info(items=item)
  File "/Users/jungyulyang/Documents/programming/pycharm/ProjectCasa/WebCrawling/decorators.py", line 80, in inner_function
    clean_bathroom = tower_info[2].replace('개', '').split('/')
TypeError: 'bool' object is not subscriptable

**Comment by whoareyouwhoami** [comment]
수정해서 올렸습니다~
