### ISSUE TITLE
아파트 면적 에러

### ISSUE THREAD

**Issue by whoareyouwhoami** [whoareyouwhoami/ProjectCasa#27]
@traceofpassion 
예측할때 아파트마다 입력할 수 있는 면적이 다른가요? 

**아파트 이름:** 한일써너스빌 
**아파트 면적:** 108
**예측 기간:** 4

이렇게 입력하니 에러가 나옵니다.
==========================>
Traceback (most recent call last):
  File "Modeling/model.py", line 97, in <module>
    result = predict_model.extract_model(input=months)
  File "Modeling/model.py", line 60, in extract_model
    total = self._model_clean()
  File "Modeling/model.py", line 47, in _model_clean
    freq='MS')
  File "/Users/PycharmProjects/casa/casa_venv/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py", line 1180, in date_range
    **kwargs,
  File "/Users/PycharmProjects/casa/casa_venv/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 376, in _generate_range
    raise ValueError("Neither `start` nor `end` can be NaT")
ValueError: Neither `start` nor `end` can be NaT

**Comment by traceofpassion** [comment]
한일써미트빌의 경우 108제곱미터 범위 안에 드는 아파트가 없는 것 같습니다. try and except 로 해당 아파트 범위가 없을 때 다른 아파트에서 데이터를 다 가져오거나, 아예 해당 아파트는 범위의 면적이 없다고 오류를 보여주도록 변경해야할 것 같습니다.
