### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by traceofpassion** [whoareyouwhoami/ProjectCasa#3]
runfile('C:/Users/trace/Documents/GitHub/ProjectCasa/WebCrawling/run_test.py', wdir='C:/Users/trace/Documents/GitHub/ProjectCasa/WebCrawling')
apartment list: 2
apartment list: 39
  city_name district_name town_name                                                url
0       서울시           강남구       개포동  https://new.land.naver.com/complexes/119219?ms...
csv checkpoint at: 강남구 개포동
apartment list: 86
apartment list: 16
apartment list: 16
apartment list: 16
apartment list: 88
apartment list: 86
apartment list: 88
apartment list: 2
Traceback (most recent call last):

  File "<ipython-input-5-79da839185ef>", line 1, in <module>
    runfile('C:/Users/trace/Documents/GitHub/ProjectCasa/WebCrawling/run_test.py', wdir='C:/Users/trace/Documents/GitHub/ProjectCasa/WebCrawling')

  File "C:\Users\trace\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\trace\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/trace/Documents/GitHub/ProjectCasa/WebCrawling/run_test.py", line 61, in <module>
    test.unit_collectURL()

  File "C:/Users/trace/Documents/GitHub/ProjectCasa/WebCrawling/run_test.py", line 58, in unit_collectURL
    self.landsite.web_collectURL()

  File "C:\Users\trace\Documents\GitHub\ProjectCasa\WebCrawling\collect.py", line 109, in web_collectURL
    apartment = apartments_list[apartment_pos]

IndexError: list index out of range

test.unit_all(start=70, end=80) 했을 때 다음과 같은 Index 에러가 뜨네요.

**Comment by whoareyouwhoami** [comment]
에러가 test.unit_collectURL() 부분을 돌려서 그런건데 그 부분은 지워주세요. test.unit_all() 하실때 CrawlTest(unit_all=True) 로 변경해주시면 됩니다. driver_type 은 현재 firefox로 되어있는데 크롬으로 돌리시려면 chrome으로 변경하시면 됩니다.
