### ISSUE TITLE
ElementClickIntercepted Exception

### ISSUE THREAD

**Issue by passionyang16** [whoareyouwhoami/ProjectCasa#4]
concat.csv 파일을 apartment_url.csv 파일로 바꿔서 실행했는데 잘 돌아가다가 갑자기 selnium 에러가 뜨네요

URL: 1
https://new.land.naver.com/complexes/8928?ms=37.496437,127.0737195,17&a=APT:JGC:ABYG&e=RETAIL
  apartment_id apartment_builder apartment_build_year apartment_build_month apartment_floor_min apartment_floor_max apartment_addr_province apartment_addr_district apartment_addr_town apartment_parking school_name school_dist school_addr_province school_addr_district school_addr_town school_students
0         8928           LG건설(주)                 2004                    06                  20                  22                     서울시                     강남구                 개포동              2.36    서울대진초등학교           1                서울특별시                  강남구          개포로109길             316
Traceback (most recent call last):
  File "/Users/jungyulyang/Documents/programming/pycharm/ProjectCasa/WebCrawling/run_test.py", line 68, in <module>
    test.unit_all(start=1, end=30)
  File "/Users/jungyulyang/Documents/programming/pycharm/ProjectCasa/WebCrawling/run_test.py", line 61, in unit_all
    self.landsite.web_collect(url_id=url_id)
  File "/Users/jungyulyang/Documents/programming/pycharm/ProjectCasa/WebCrawling/collect.py", line 203, in web_collect
    tower_area = self._tower_area()
  File "/Users/jungyulyang/Documents/programming/pycharm/ProjectCasa/WebCrawling/collect.py", line 322, in _tower_area
    price.click()
  File "/opt/anaconda3/envs/projects/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/opt/anaconda3/envs/projects/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/opt/anaconda3/envs/projects/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/anaconda3/envs/projects/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a href="javascript:void(0);" class="tab_item" id="detailTab2" role="tab" aria-controls="detailContents2" aria-selected="true" data-nclk="DEC.sise">...</a> is not clickable at point (391, 23). Other element would receive the click: <span class="text">...</span>
  (Session info: headless chrome=80.0.3987.163)

**Comment by whoareyouwhoami** [comment]
다시 돌려도 똑같은 에러가 뜨나요?
